Resources:
  AgentVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  AgentSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AgentVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1a"

  # The VPC needs to have access to the SSM service endpoint
  # for fetching secrets
  AgentSSMVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssm'
      VpcId: !Ref AgentVPC
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref AgentSubnet
      SecurityGroupIds:
        - !Ref AgentVpcEndpointSecurityGroup

  # Allow traffic from the VPC to the ECR service endpoints
  ECRApiVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      VpcEndpointType: Interface
      VpcId: !Ref AgentVPC
      SubnetIds:
        - !Ref AgentSubnet
      SecurityGroupIds:
        - !Ref AgentVpcEndpointSecurityGroup

  ECRDkrVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      VpcEndpointType: Interface
      VpcId: !Ref AgentVPC
      SubnetIds:
        - !Ref AgentSubnet
      SecurityGroupIds:
        - !Ref AgentVpcEndpointSecurityGroup 

  AgentVpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow VPC Endpoint Communication
      VpcId: !Ref AgentVPC
      SecurityGroupIngress:
        - IpProtocol: -1 
          CidrIp: '10.0.0.0/16'  # Adjust CIDR block as needed
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'

  AgentCluster:
    Type: AWS::ECS::Cluster

  DockerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: python-agent-example

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole  # You can name this role, or let CloudFormation name it
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSSecretsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:DescribeParameters
                  - kms:Decrypt  # Include if you're using KMS-encrypted secrets
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ecs/python-agent-example/*"
        - PolicyName: ECSTaskExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  PythonAgentExampleTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Cpu: "2048"
      Memory: "4096"
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: python-agent-example 
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${DockerRepository}:latest"
          Essential: true
          Secrets:
            - Name: LIVEKIT_URL
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ecs/python-agent-example/livekit-url"
            - Name: LIVEKIT_API_KEY
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ecs/python-agent-example/livekit-api-key"
            - Name: LIVEKIT_API_SECRET
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ecs/python-agent-example/livekit-api-secret"

  PythonAgentExampleService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref AgentCluster 
      DesiredCount: 1 # Initially set to 0 because the image doesn't exist yet
      TaskDefinition: !Ref PythonAgentExampleTaskDefinition 
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref AgentSubnet 
          SecurityGroups:
            - !Ref AgentVpcEndpointSecurityGroup 